### PR TITLE
Added `untracked` function

### PR DESCRIPTION
**Pull request by XantreGodlike**
Resolves https://github.com/preactjs/signals/issues/378

As mentioned in the proposal this allows us to write effects that essentially aren't re-executed by the signals that get accessed in the function body of `untracked`.

Allowing functionality like

```js
function reaction(sender, listener) {
  effect(() => {
    const value = sender();
    untracked(() => {
      listener(value);
    });
  }
}
```

### CODE REVIEW

**Comment by XantreGodlike** [comment]
@andrewiggins can you review or say why its shouldn't be added?)

**Comment by andrewiggins** [comment]
Hey! One question that comes to mind for me is what use case does this help that use `const value = signal.peek()` doesn't work for?

**Comment by XantreGodlike** [comment]
Some reasons is specified in proposal linked to the PR.
But shortly: its useful for creating utils that works with callbacks. Most of reactive runtime provides `untracked`, so it's common pattern, that allows to manipulate reactivity not in user side, but in consumer side. 
Yes, I can emulate untracked with computed, but it has too much overhead IMHO. 
```js
const untracked = (callback) => computed(callback).peek()
```

**Comment by andrewiggins** [comment]
Oh whoops! I missed the linked proposal. Lemme take a look and mull it over with the team

**Comment by XantreGodlike** [comment]
I think this thing are essential for writing Store-like primitives and dealing with it without tricks

**Comment by XantreGodlike** [comment]
@andrewiggins when you will return with feedback?

**Comment by andrewiggins** [comment]
I have some vacation coming up so will be away for a week or two. Though if other core team members have thoughts, no need to block on me

**Comment by XantreGodlike** [comment]
@JoviDeCroock what do you think about `untracked`?

**Comment by JoviDeCroock** [comment]
This looks good to me, tests seem to be failing and needs a changeset

**Comment by XantreGodlike** [comment]
> This looks good to me, tests seem to be failing and needs a changeset

Fixed

**Review by JoviDeCroock — APPROVED** [review]

**Comment by betula** [comment]
Thanks a lot👍

**Pull request merged**
