### PR TITLE
fix: Correct invalid React peerDep versions

### LINKED ISSUE #102: pnpm unmet peer react@"17.x | 18.x": found 17.0.2
i tryed to install `"@preact/signals-react": "^1.0.0",` using `pnpm 7.11.0` and got the following error: 

```
.
└─┬ @preact/signals-react 1.0.0
  └── ✕ unmet peer react@"17.x | 18.x": found 17.0.2
```

so `17.0.2` should work fine?
i am not sure if its a pnpm bug but may you could change the peerDependencies in a way, that pnpm understands it.

### PR DESCRIPTION
**Pull request by rschristian**
Fixes #102 

Simple typo

### CODE REVIEW

**Review by JoviDeCroock — APPROVED** [review]

**Comment by JoviDeCroock** [comment]
Will need to add a changeset! 😅

**Comment by rschristian** [comment]
Was on my way to do

**Comment by JoviDeCroock** [comment]
Haha no worries, just wanted to remind you after my quick checkmark 😅

**Comment by marvinhagemeister** [comment]
Was just running into this right now. Awesome to see that a fix is already merged 👍

**Pull request merged**
