### PR TITLE
Create deepsignal package

### PR DESCRIPTION
**Pull request by luisherranz**
Initial version of the `deepsignal` package.

### CODE REVIEW

**Comment by luisherranz** [comment]
Sorry, wrong repository 😅

**Comment by rschristian** [comment]
Adding this here just in case it's helpful, but someone did create a deep signal package awhile back: https://github.com/EthanStandel/deepsignal

Not sure if you've seen this or not

**Comment by luisherranz** [comment]
Yes, we've been talking about the possible implementations here: https://github.com/preactjs/signals/issues/4

**Comment by rschristian** [comment]
Ah, fair enough!

**Comment by luisherranz** [comment]
For reference, this is the final deep signals package: https://github.com/luisherranz/deepsignal

**Pull request closed without merging**
