### PR TITLE
Small fixes to core

### PR DESCRIPTION
**Pull request by elliotwaite**
Just some suggestions I noticed while reading over the code. Mostly typo fixes in comments, but I also thought using the parameter name dep instead of sub in those arrow functions made more sense, and then I noticed that in one of the tests, the code didn't seem to align with the comment at the top of the test, it looks like that eSpy function should be reading d.value.

Thanks for building this library. I'm looking forward to trying it out some more.

Note: This PR is a redo of https://github.com/preactjs/signals/pull/123

### CODE REVIEW

**Comment by elliotwaite** [comment]
I was trying to rebase the old PR and messed something up and was getting confused, so I just created a new PR.

I added the changset from `pnpm changest`, but I wasn't sure how descriptive the changeset text should be so I just used the same text as the title of the PR, "Small fixes to core," but let me know if the changeset should be more descriptive.

**Comment by marvinhagemeister** [comment]
@elliotwaite Awesome thanks a bunch! The "small fixes to core" is a bit abstract. Maybe something like "Fix incorrectly named variables and address typos in code comments" would better describe the changes in this PR?

**Comment by elliotwaite** [comment]
@marvinhagemeister That sounds good to me. I updated it.

**Review by marvinhagemeister — APPROVED** [review]
Sweet, thank you so much  🙌

**Pull request merged**
